name = "chal1-web"
challenge = "Chal1"
image = "chal1-web" # default normalize name
# entrypoint = null
enabled = true
# max_per_container = 0
# max_containers = 0
# max_concurrent_jobs = 0
timeout = 30
default_counter = 50
# ignore_connection_info = false
auto_add = "end"
insert_into_rounds = true
